// TODO THIS SHOULD BE ABLE TO BE CALLED BY ANYONE TO CHECK ANYONE'S TASK INFO OR ITS OWN, IF NO INDEX0 SHOULD CHECK IT'S OWN, IF NOT SHOULD CHECK THAT USER'S TASK
// TODO ALSO IT SHOULD SAVE EACH USERS TASKS BY ID AND NOT BY NAME, CUZ PEOPLE MIGHT CHANGE IT'S NAME
